name: Set publish date for GitHub Pages
# run when pushing to main
on:
    push:
        branches: [main]

# allow the action to write back to the repo
permissions:
    contents: write

jobs:
    set-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # ensures the token is available for pushing commits
                  persist-credentials: true

            - name: Generate index.html with UTC publish timestamp
              run: |
                  set -e
                  PUBLISH="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
                  echo "Publish date: $PUBLISH"
                  # Replace placeholder in template — produces index.html
                  sed "s|__PUBLISH_DATE__|${PUBLISH}|g" index.template.html > index.html
                  # Only commit if index.html changed (avoids noise)
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  if ! git diff --quiet --exit-code index.html; then
                    git add index.html
                    git commit -m "ci: set publish date ${PUBLISH}"
                    git push origin HEAD:main
                  else
                    echo "index.html is unchanged; nothing to commit"
                  fi
